name: 'Generate awesome wallpapers'
description: 'A javascript action to generate awesome wallpapers with HuggingFace Inference API (serverless)'
author: huuquyet

# Add your action's branding here. This will appear on the GitHub Marketplace. Icons from https://feathericons.com/
branding:
  icon: 'image'
  color: 'yellow'

# Enter the prompt to generate awesome wallpapers
inputs:
  prompt: # id of input
    description: "Input prompt send to the action"
    required: false
  random:
    description: "The flag to set random prompt"
    required: false
    default: 'false'

# Ouput the random model and prompt that use to generate
outputs:
  model_id:
    description: The random model get from list
  prompt:
    description: The random prompt get from json file

runs:
  using: 'node20'
  main: dist/index.js
