name: 'Generate awesome wallpapers'
description: 'Generate awesome wallpapers with HuggingFace API inference'
author: huuquyet

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

runs:
  using: 'node20'
  main: dist/index.ts
