# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: generate-wallpapers-with-Python

on:
  # Allows to manually run the job at any time
  workflow_dispatch:
  # Run on every push or pull request on main branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

permissions:
  contents: write

# Only a single workflow in the same concurrency will run at the same time
# concurrency:
#   group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref || github.event.pull_request.head.label }}'
#   cancel-in-progress: true

jobs:
  generate_wallpaper:
    name: Generate awesome wallpapers with Python
    runs-on: ubuntu-latest

    steps:
    # Checkout the main branch
    - uses: actions/checkout@v4

    # Setup Python environment
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Linting with ruff
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true

    # Testing
    # - name: Test with pytest
      # run: |
        # pip install pytest
        # pytest

    # Generate awesome wallpapers
    - name: Generate awesome wallpapers
      env: 
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      run: python generate.py

    # Push awesome wallpapers to main branch
    # Note: the following account information will not work on GHES
    - name: Push the awesome wallpapers to main branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m ":robot: Generated awesome wallpaper [skip ci]"
        git push
